/**
 * The fake `nax generate` and `nax rules lint` for config jobs (S3 §5). `generate` writes CLAUDE.md and AGENTS.md from
 * `.nax/context.md`; `--all-packages` writes `<pkg>/CLAUDE.md` for every `.nax/mono/<pkg>/context.md`. Markers in the
 * input files make them fail: `FAKE_GENERATE_FAIL` in a context file, `FAKE_LINT_FAIL` in a rule.
 * `FAKE_NAX_GENERATE_SLEEP_MS` holds `generate` (cancel / restart tests).
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

export interface ToolAnswer {
  readonly stdout: string;
  readonly stderr: string;
  readonly code: number;
}

const flagValue = (args: readonly string[], name: string): string | undefined => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};

function walk(dir: string, name: (file: string) => boolean): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);
    return statSync(path).isDirectory() ? walk(path, name) : name(entry) ? [path] : [];
  });
}

function hold(): void {
  const ms = Number(process.env['FAKE_NAX_GENERATE_SLEEP_MS'] ?? 0);
  if (ms > 0) Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

function generate(args: readonly string[], dir: string): ToolAnswer {
  hold();
  if (args.includes('--all-packages')) {
    const mono = join(dir, '.nax', 'mono');
    const written = walk(mono, (file) => file === 'context.md').map((path) => {
      const text = readFileSync(path, 'utf8');
      if (text.includes('FAKE_GENERATE_FAIL')) throw new Error(`generate failed for ${relative(dir, path)}`);
      const pkg = relative(mono, dirname(path));
      mkdirSync(join(dir, pkg), { recursive: true });
      writeFileSync(join(dir, pkg, 'CLAUDE.md'), `<!-- generated by fake nax -->\n${text}`);
      return `${pkg}/CLAUDE.md`;
    });
    return { stdout: `generated ${written.length} package file(s)`, stderr: '', code: 0 };
  }
  const context = join(dir, '.nax', 'context.md');
  if (!existsSync(context)) return { stdout: '', stderr: 'nax generate: .nax/context.md not found', code: 1 };
  const text = readFileSync(context, 'utf8');
  if (text.includes('FAKE_GENERATE_FAIL')) return { stdout: '', stderr: 'nax generate: context.md is malformed', code: 1 };
  for (const name of ['CLAUDE.md', 'AGENTS.md']) writeFileSync(join(dir, name), `<!-- generated by fake nax -->\n${text}`);
  return { stdout: 'generated 2 file(s)', stderr: '', code: 0 };
}

function rulesLint(dir: string): ToolAnswer {
  const bad = walk(join(dir, '.nax', 'rules'), (file) => file.endsWith('.md')).find((path) => readFileSync(path, 'utf8').includes('FAKE_LINT_FAIL'));
  return bad
    ? { stdout: '', stderr: `rules lint: ${relative(dir, bad)}: banned marker FAKE_LINT_FAIL`, code: 1 }
    : { stdout: 'rules lint: ok', stderr: '', code: 0 };
}

export function answerConfigTool(args: readonly string[], cwd: string): ToolAnswer | null {
  const dir = flagValue(args, '-d') ?? cwd;
  try {
    if (args[0] === 'generate') return generate(args, dir);
    if (args[0] === 'rules' && args[1] === 'lint') return rulesLint(dir);
  } catch (error) {
    return { stdout: '', stderr: `nax: ${(error as Error).message}`, code: 1 };
  }
  return null;
}
